import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { NextUIProviders } from './next-ui/provider'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { AuthProvider } from "./api/auth/provider";
import FirebaseProvider from "./firebase/provider";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextUIProviders>
          <AuthProvider>
            <FirebaseProvider>
              {children}
            </FirebaseProvider>
          </AuthProvider>
        </NextUIProviders>
      </body>
    </html>
  )
}
